/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Sanitizes the JSON-shaped canvas strokes without changing their public shape.
 * Invalid entries/points are discarded; valid strokes need at least two points.
 */
export declare function sanitizeStrokes(value: any): any
