//! Block 2, planner half: folding a journal must reproduce the item list the
//! TypeScript `PlannerStore.reduce` produces.
//!
//! The fixture is generated by scripts/gen-planner-fixture.ts against the real
//! reducer, with both `Date.now` and the local calendar day pinned — relative
//! days ("today", "tomorrow") would otherwise make the expectation drift.

use grayspace_app::journal::JournalEntry;
use grayspace_app::planner::{fold, normalize_day, reduce, PlanItem, PlannerState, Today};
use serde_json::Value;

struct Fixture {
    entries: Vec<JournalEntry>,
    items: Vec<Value>,
    today: Today,
}

fn load() -> Fixture {
    let parsed: Value = serde_json::from_str(include_str!("fixtures/planner-projection.json"))
        .expect("fixture parses");
    Fixture {
        entries: parsed["entries"]
            .as_array()
            .expect("entries")
            .iter()
            .map(|e| serde_json::from_value(e.clone()).expect("entry parses"))
            .collect(),
        items: parsed["items"].as_array().expect("items").clone(),
        today: Today(parsed["today"].as_str().expect("today").to_owned()),
    }
}

fn check(actual: &PlanItem, expected: &Value) {
    let at = &actual.id;
    assert_eq!(
        actual.title,
        expected["title"].as_str().unwrap(),
        "{at}: title"
    );
    assert_eq!(
        actual.note,
        expected["note"].as_str().unwrap_or(""),
        "{at}: note"
    );
    assert_eq!(
        actual.project.as_deref(),
        expected["project"].as_str(),
        "{at}: project"
    );
    assert_eq!(actual.day.as_deref(), expected["day"].as_str(), "{at}: day");
    assert_eq!(
        actual.time.as_deref(),
        expected["time"].as_str(),
        "{at}: time"
    );
    assert_eq!(
        actual.done,
        expected["done"] == Value::Bool(true),
        "{at}: done"
    );
    assert_eq!(
        actual.created_by,
        expected["createdBy"].as_str().unwrap(),
        "{at}: createdBy"
    );
    assert_eq!(
        actual.order,
        expected["order"].as_f64().unwrap(),
        "{at}: order"
    );
    assert_eq!(
        actual.created_at,
        expected["createdAt"].as_f64().unwrap(),
        "{at}: createdAt"
    );
    assert_eq!(
        actual.updated_at,
        expected["updatedAt"].as_f64().unwrap(),
        "{at}: updatedAt"
    );
    assert_eq!(
        actual.version,
        expected["version"].as_f64().unwrap(),
        "{at}: version"
    );

    let expected_attachments = expected
        .get("attachments")
        .and_then(Value::as_array)
        .map(|items| {
            items
                .iter()
                .map(|v| v.as_str().unwrap().to_owned())
                .collect::<Vec<_>>()
        });
    assert_eq!(
        actual.attachments, expected_attachments,
        "{at}: attachments"
    );
}

#[test]
fn folding_the_fixture_reproduces_the_typescript_items() {
    let fixture = load();
    let state = fold(fixture.entries.iter(), PlannerState::new(), &fixture.today)
        .expect("fixture contains no day that aborts the fold");
    let actual: Vec<&PlanItem> = state.values().collect();

    assert_eq!(
        actual.iter().map(|i| i.id.as_str()).collect::<Vec<_>>(),
        fixture
            .items
            .iter()
            .map(|i| i["id"].as_str().unwrap())
            .collect::<Vec<_>>(),
        "item ids or their order differ"
    );
    for (item, expected) in actual.iter().zip(&fixture.items) {
        check(item, expected);
    }
}

/// The create path coerces `order` and the update path does not. Reading both
/// strictly passed every other case and silently lost this one.
#[test]
fn create_coerces_order_while_update_does_not() {
    let fixture = load();
    let state = fold(fixture.entries.iter(), PlannerState::new(), &fixture.today).unwrap();
    let created = state.get("p10").expect("p10 was created with order \"5\"");
    assert_eq!(
        created.order, 5.0,
        "plan.create must coerce a numeric string"
    );
}

#[test]
fn folding_is_deterministic_and_splits_cleanly() {
    let fixture = load();
    let whole = fold(fixture.entries.iter(), PlannerState::new(), &fixture.today).unwrap();
    let split = fixture.entries.len() / 2;
    let head = fold(
        fixture.entries[..split].iter(),
        PlannerState::new(),
        &fixture.today,
    )
    .unwrap();
    let tail = fold(fixture.entries[split..].iter(), head, &fixture.today).unwrap();
    assert_eq!(
        whole, tail,
        "a snapshot plus its tail must equal the whole run"
    );
}

/// `plan.update` uses the throwing day validator, so a malformed day stops the
/// fold instead of being dropped. Replay must not silently disagree with the
/// live store about which items exist.
#[test]
fn a_malformed_day_in_an_update_aborts_the_fold() {
    let entry: JournalEntry = serde_json::from_str(
        r#"{"seq":1,"at":1789061000000,"phase":"commit","actorId":"user",
            "type":"plan.update","target":"plan:p1","payload":{"day":"13/09/2026"}}"#,
    )
    .unwrap();

    let mut state = PlannerState::new();
    state.insert(
        "p1".to_owned(),
        PlanItem {
            id: "p1".to_owned(),
            title: "Existing".to_owned(),
            note: String::new(),
            project: None,
            day: None,
            time: None,
            done: false,
            created_by: "user".to_owned(),
            order: 0.0,
            created_at: 1.0,
            updated_at: 1.0,
            version: 1.0,
            attachments: None,
        },
    );

    let today = Today("2026-09-13".to_owned());
    assert!(reduce(&state, &entry, &today).is_err());
}

#[test]
fn relative_days_resolve_against_the_injected_calendar() {
    let today = Today("2026-03-01".to_owned());
    let day = |raw: &str| {
        normalize_day(Some(&Value::String(raw.to_owned())), &today)
            .unwrap()
            .unwrap()
    };
    assert_eq!(day("today"), "2026-03-01");
    assert_eq!(day("tomorrow"), "2026-03-02");
    // Crossing a month boundary backwards, in a non-leap year.
    assert_eq!(day("yesterday"), "2026-02-28");
}

#[test]
fn leap_days_are_accepted_only_in_leap_years() {
    let today = Today("2026-09-13".to_owned());
    let parse = |raw: &str| normalize_day(Some(&Value::String(raw.to_owned())), &today);
    assert_eq!(parse("2024-02-29").unwrap(), Some("2024-02-29".to_owned()));
    assert!(parse("2026-02-29").is_err(), "2026 is not a leap year");
    // A single-digit month and day are accepted and zero-padded on the way out.
    assert_eq!(parse("2026-1-5").unwrap(), Some("2026-01-05".to_owned()));
}
