/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function sanitizeScrollback(text: string, limit: number): string

export declare function stripAnsiText(text: string): string

export declare function writeTextAtomic(path: string, text: string, keepBackup: boolean): Promise<unknown>
