/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Combined hot path for persisting one terminal's screen: sanitize, then cap.
 * Synchronous and cheap enough to run on the JS thread (a capped 64 KiB walk),
 * but it replaces two full-string passes with zero-copy slicing in Rust, so a
 * multi-megabyte build log costs a scan instead of tens of thousands of
 * per-character string operations before every scrollback save.
 */
export declare function sanitizeScrollback(text: string, limit: number): string

/**
 * Public twin of the internal stripper: one string in, one
 * string out. The napi bridge for a single `String` is one UTF-16 → UTF-8
 * copy — the cheap kind of bridge (see the note on `write_text_atomic`) —
 * while the per-character scan itself runs in Rust. Terminal output routes
 * every streamed chunk of every CLI reply through here, which used to be a
 * regex-heavy JavaScript pass per chunk on the renderer's main thread.
 */
export declare function stripAnsiText(text: string): string

/**
 * JS-facing entry point: looks synchronous but returns a `Promise` backed by
 * `AsyncTask`, so the file write + fsync + rename run off the Node/Electron
 * main thread and never block IPC, PTY output, or the renderer's canvas.save
 * round-trip.
 *
 * It takes the **already-serialized text**, not the object. The previous
 * signature was `write_json_atomic(path, value: serde_json::Value)`, and that
 * `Value` was materialized by napi on the JS thread *before* the AsyncTask
 * was ever queued: converting one full canvas (200k stroke points) into a
 * `serde_json::Value` tree blocked the main process for ~176 ms, against
 * ~40 ms for V8's own `JSON.stringify` of the same object and ~10 ms for the
 * write itself. The "off-thread" writer was the single largest main-thread
 * stall on the autosave path. Handing Rust a `String` costs one UTF-16 → UTF-8
 * copy and moves everything that actually touches the disk off-thread, which
 * is what the crate was for.
 */
export declare function writeTextAtomic(path: string, text: string, keepBackup: boolean): Promise<unknown>
