/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Combined hot path for persisting one terminal's screen: sanitize, then cap.
 * Synchronous and cheap enough to run on the JS thread (a capped 64 KiB walk),
 * but it replaces two full-string passes with zero-copy slicing in Rust, so a
 * multi-megabyte build log costs a scan instead of tens of thousands of
 * per-character string operations before every scrollback save.
 */
export declare function sanitizeScrollback(text: string, limit: number): string

/**
 * JS-facing entry point: looks synchronous but returns a `Promise` backed by
 * `AsyncTask`, so the JSON serialize + file write + fsync run off the
 * Node/Electron main thread and never block IPC, PTY output, or the
 * renderer's canvas.save round-trip.
 */
export declare function writeJsonAtomic(path: string, value: any): Promise<unknown>
