/* auto-generated by NAPI-RS */
/* eslint-disable */
export interface ReindexNoteInput {
  id: string
  title: string
  content: string
  alive: boolean
}

export interface ReindexNoteResult {
  id: string
  links: Array<string>
  unresolved: Array<string>
}

export declare function reindexNotes(notes: Array<ReindexNoteInput>, syntax: string): Array<ReindexNoteResult>
