//! Proves the Rust journal hashes exactly as the TypeScript one does.
//!
//! The fixture is generated by scripts/gen-journal-fixture.mjs running the real
//! computeEntryHash, so a failure here means Rust and TypeScript disagree about
//! the canonical form — the chain would break the moment either wrote an entry
//! the other had to verify.

use orcspace_app::journal::{
    canonical_hash_input_for_debug, compute_entry_hash, format_js_number, verify_chain,
    JournalEntry, GENESIS_HASH,
};

fn load_fixture() -> Vec<JournalEntry> {
    let raw = include_str!("fixtures/journal-chain.ndjson");
    raw.lines()
        .filter(|line| !line.trim().is_empty())
        .map(|line| serde_json::from_str::<JournalEntry>(line).expect("fixture line parses"))
        .collect()
}

#[test]
fn every_fixture_hash_matches_the_typescript_one() {
    let entries = load_fixture();
    assert!(!entries.is_empty(), "fixture must not be empty");

    let mut prev = GENESIS_HASH.to_owned();
    for entry in &entries {
        let computed = compute_entry_hash(&prev, entry);
        let recorded = entry.hash.as_deref().expect("fixture entries carry a hash");
        assert_eq!(
            recorded, computed,
            "hash mismatch at seq {} — Rust and TypeScript disagree on the canonical form",
            entry.seq
        );
        prev = computed;
    }
}

#[test]
fn the_whole_fixture_chain_verifies() {
    let entries = load_fixture();
    assert_eq!(verify_chain(&entries), Ok(()));
}

#[test]
fn a_tampered_payload_breaks_the_chain() {
    let mut entries = load_fixture();
    let target = entries
        .iter_mut()
        .find(|entry| entry.payload.is_some())
        .expect("fixture has an entry with a payload");
    target.payload = Some(serde_json::json!({ "tampered": true }));

    assert!(
        verify_chain(&entries).is_err(),
        "a changed payload must not still verify"
    );
}

/// The number cases the hand-written writer exists for. Each expectation is
/// what `JSON.stringify` produces; serde_json's own writer differs on several.
#[test]
fn numbers_format_the_way_javascript_writes_them() {
    let cases: &[(f64, &str)] = &[
        (0.0, "0"),
        (-0.0, "0"),
        (1.0, "1"),
        (-1.0, "-1"),
        (100.5, "100.5"),
        (-4617.767343849823, "-4617.767343849823"),
        (1.2047768476488074, "1.2047768476488074"),
        // Exponent-form boundaries: JavaScript switches out at 1e21 and 1e-7.
        (1e20, "100000000000000000000"),
        (1e21, "1e+21"),
        (1e-6, "0.000001"),
        (1e-7, "1e-7"),
        (1.5e22, "1.5e+22"),
        (9007199254740991.0, "9007199254740991"),
    ];
    for (value, expected) in cases {
        assert_eq!(
            &format_js_number(*value),
            expected,
            "format_js_number({value}) diverged from JSON.stringify"
        );
    }
}

/// Verifies a journal this app actually wrote, rather than one built to be
/// verified. A real file carries payload shapes no fixture would think of, and
/// it is a tail rather than a full chain — it starts wherever the log was
/// rotated — so the walk is seeded from the first entry's own prevHash instead
/// of from genesis.
///
/// Ignored by default because it needs a file that is not in the repository
/// (journals contain the user's paths and commands):
///   ORCSPACE_JOURNAL=<path> cargo test --test journal_parity -- --ignored
#[test]
#[ignore = "needs a real journal: set ORCSPACE_JOURNAL"]
fn verifies_a_real_journal_file() {
    let path = std::env::var("ORCSPACE_JOURNAL")
        .expect("set ORCSPACE_JOURNAL to a command-journal.ndjson path");
    let raw = std::fs::read_to_string(&path).expect("journal file is readable");

    let entries: Vec<JournalEntry> = raw
        .lines()
        .filter(|line| !line.trim().is_empty())
        .map(|line| serde_json::from_str::<JournalEntry>(line).expect("journal line parses"))
        .collect();
    assert!(entries.len() > 1, "journal has entries to check");

    let mut prev = entries[0]
        .prev_hash
        .clone()
        .expect("the first entry records the hash it follows");
    let mut checked = 0usize;
    for entry in &entries {
        let computed = compute_entry_hash(&prev, entry);
        let recorded = entry.hash.as_deref().expect("entries carry a hash");
        assert_eq!(
            recorded, computed,
            "hash mismatch at seq {} in {path}",
            entry.seq
        );
        prev = computed;
        checked += 1;
    }
    println!("verified {checked} real journal entries");
}

/// Regression. serde_json's default float parser is fast but not always
/// correctly rounded: it read this real canvas coordinate as the double one ULP
/// above it, which printed back as 3844.78979830168 and broke the chain at a
/// real entry after 168 good ones. The fault was in parsing, not formatting, so
/// this asserts on a value that made the round trip through serde_json rather
/// than on a literal. Guards the float_roundtrip feature staying enabled.
#[test]
fn float_payloads_survive_the_parse_exactly() {
    let raw = concat!(
        r#"{"seq":21777,"at":1789062148851,"phase":"intent","actorId":"user","#,
        r#""type":"canvas.import","target":"canvas:main","payload":{"#,
        r#""x":3844.7897983016796,"y":1181.8581761894222,"zoom":0.8925206405937184}}"#
    );
    let entry: JournalEntry = serde_json::from_str(raw).expect("parses");
    let canonical = canonical_hash_input_for_debug(GENESIS_HASH, &entry);

    for expected in ["3844.7897983016796", "1181.8581761894222", "0.8925206405937184"] {
        assert!(
            canonical.contains(expected),
            "{expected} did not survive the parse/print round trip:\n{canonical}"
        );
    }
}

#[test]
fn non_finite_numbers_become_null_like_json_stringify() {
    assert_eq!(format_js_number(f64::NAN), "null");
    assert_eq!(format_js_number(f64::INFINITY), "null");
    assert_eq!(format_js_number(f64::NEG_INFINITY), "null");
}

/// Debug helper: dumps the canonical hash input for one entry so it can be
/// diffed against the JavaScript one byte for byte.
///   ORCSPACE_JOURNAL=<path> ORCSPACE_SEQ=<seq> ORCSPACE_CANON_OUT=<file> \
///     cargo test --test journal_parity dumps_canonical -- --ignored --nocapture
#[test]
#[ignore = "debug helper"]
fn dumps_canonical_form() {
    let path = std::env::var("ORCSPACE_JOURNAL").expect("ORCSPACE_JOURNAL");
    let seq: u64 = std::env::var("ORCSPACE_SEQ").expect("ORCSPACE_SEQ").parse().unwrap();
    let out = std::env::var("ORCSPACE_CANON_OUT").expect("ORCSPACE_CANON_OUT");
    let raw = std::fs::read_to_string(&path).unwrap();
    let entry = raw
        .lines()
        .filter(|l| !l.trim().is_empty())
        .map(|l| serde_json::from_str::<JournalEntry>(l).unwrap())
        .find(|e| e.seq == seq)
        .expect("seq present");
    let prev = entry.prev_hash.clone().unwrap();
    std::fs::write(&out, orcspace_app::journal::canonical_hash_input_for_debug(&prev, &entry)).unwrap();
}
