//! Block 2 parity: folding a journal in Rust must land on the snapshot the
//! TypeScript reducer produces.
//!
//! The fixture is generated by scripts/gen-projection-fixture.ts running the
//! real `CanvasStore.reduce`, with `Date.now` pinned so the sanitizers' missing
//! -timestamp fallbacks are reproducible. A failure here means a replayed
//! canvas would differ from the one Electron shows — silently, and only for the
//! entries that happened to hit the diverging branch.

use orcspace_app::journal::JournalEntry;
use orcspace_app::projection::{fold, list_widgets, CanvasState, Clock};
use serde_json::Value;

struct Fixture {
    entries: Vec<JournalEntry>,
    snapshot: Value,
    clock: Clock,
}

fn load() -> Fixture {
    let raw = include_str!("fixtures/canvas-projection.json");
    let parsed: Value = serde_json::from_str(raw).expect("fixture parses");
    let entries = parsed["entries"]
        .as_array()
        .expect("fixture has entries")
        .iter()
        .map(|entry| serde_json::from_value::<JournalEntry>(entry.clone()).expect("entry parses"))
        .collect();
    let clock = Clock(parsed["fixedNow"].as_f64().expect("fixture pins Date.now"));
    Fixture { entries, snapshot: parsed["snapshot"].clone(), clock }
}

fn number(value: &Value) -> f64 {
    value.as_f64().unwrap_or_else(|| panic!("expected a number, got {value}"))
}

#[test]
fn folding_the_fixture_reproduces_the_typescript_snapshot() {
    let fixture = load();
    let state = fold(fixture.entries.iter(), CanvasState::default(), fixture.clock);

    let expected_widgets = fixture.snapshot["widgets"].as_array().expect("widgets");
    let actual_widgets = list_widgets(&state);

    assert_eq!(
        actual_widgets.len(),
        expected_widgets.len(),
        "widget count differs\n  rust: {:?}\n  ts:   {:?}",
        actual_widgets.iter().map(|w| &w.id).collect::<Vec<_>>(),
        expected_widgets
            .iter()
            .map(|w| w["id"].as_str().unwrap_or("?"))
            .collect::<Vec<_>>()
    );

    // Order is compared, not just membership: the snapshot lists widgets in
    // insertion order and the renderer draws them in that order.
    for (index, (actual, expected)) in actual_widgets.iter().zip(expected_widgets).enumerate() {
        let at = format!("widget {index}");
        assert_eq!(actual.id, expected["id"].as_str().unwrap(), "{at}: id");
        assert_eq!(actual.title, expected["title"].as_str().unwrap(), "{at}: title");
        assert_eq!(
            actual.kind.as_deref(),
            expected["kind"].as_str(),
            "{at}: kind"
        );
        assert_eq!(actual.x, number(&expected["x"]), "{at}: x");
        assert_eq!(actual.y, number(&expected["y"]), "{at}: y");
        assert_eq!(actual.w, number(&expected["w"]), "{at}: w");
        assert_eq!(actual.h, number(&expected["h"]), "{at}: h");
        assert_eq!(actual.z, number(&expected["z"]), "{at}: z");
        assert_eq!(actual.maximized, expected["maximized"] == Value::Bool(true), "{at}: maximized");
        assert_eq!(actual.version, number(&expected["version"]), "{at}: version");
        assert_eq!(actual.updated_at, number(&expected["updatedAt"]), "{at}: updatedAt");
    }

    let camera = &fixture.snapshot["camera"];
    assert_eq!(state.camera.x, number(&camera["x"]), "camera x");
    assert_eq!(state.camera.y, number(&camera["y"]), "camera y");
    assert_eq!(state.camera.zoom, number(&camera["zoom"]), "camera zoom");

    let expected_strokes = fixture.snapshot["strokes"].as_array().expect("strokes");
    assert_eq!(state.strokes.len(), expected_strokes.len(), "stroke count");
    for (actual, expected) in state.strokes.iter().zip(expected_strokes) {
        assert_eq!(actual.id, expected["id"].as_str().unwrap());
        assert_eq!(actual.color, expected["color"].as_str().unwrap());
        let points = expected["points"].as_array().unwrap();
        assert_eq!(actual.points.len(), points.len(), "point count in {}", actual.id);
        for (point, expected_point) in actual.points.iter().zip(points) {
            assert_eq!(point.x, number(&expected_point["x"]));
            assert_eq!(point.y, number(&expected_point["y"]));
        }
    }

    let expected_connections = fixture.snapshot["connections"].as_array().expect("connections");
    assert_eq!(
        state.connections.len(),
        expected_connections.len(),
        "connection count\n  rust: {:?}",
        state.connections.iter().map(|c| &c.id).collect::<Vec<_>>()
    );
    for (actual, expected) in state.connections.iter().zip(expected_connections) {
        assert_eq!(actual.id, expected["id"].as_str().unwrap());
        assert_eq!(actual.from, expected["from"].as_str().unwrap());
        assert_eq!(actual.to, expected["to"].as_str().unwrap());
        assert_eq!(actual.born_at, number(&expected["bornAt"]));
    }

    assert_eq!(state.version, number(&fixture.snapshot["version"]), "canvas version");
}

/// Replaying the same run twice must land in the same place — otherwise a
/// recovery that folds the journal would drift from the live state.
#[test]
fn folding_is_deterministic() {
    let fixture = load();
    let once = fold(fixture.entries.iter(), CanvasState::default(), fixture.clock);
    let twice = fold(fixture.entries.iter(), CanvasState::default(), fixture.clock);
    assert_eq!(once, twice);
}

/// Folding in two passes must equal folding in one: this is what lets a
/// snapshot be loaded and only the journal tail replayed on top.
#[test]
fn folding_a_tail_onto_a_snapshot_equals_folding_the_whole_run() {
    let fixture = load();
    let split = fixture.entries.len() / 2;

    let whole = fold(fixture.entries.iter(), CanvasState::default(), fixture.clock);
    let head = fold(fixture.entries[..split].iter(), CanvasState::default(), fixture.clock);
    let tail = fold(fixture.entries[split..].iter(), head, fixture.clock);

    assert_eq!(whole, tail);
}

#[test]
fn non_commit_entries_change_nothing() {
    let fixture = load();
    let mut intents = fixture.entries.clone();
    for entry in &mut intents {
        entry.phase = "intent".to_owned();
    }
    let state = fold(intents.iter(), CanvasState::default(), fixture.clock);
    assert_eq!(state, CanvasState::default());
}

/// The real check: fold a journal this app actually wrote and compare against
/// the snapshot the TypeScript reducer produced from the same file.
///
/// Generate the reference first:
///   node scripts/dump-canvas-snapshot.ts <journal.ndjson> <snapshot.json>
/// then:
///   ORCSPACE_JOURNAL=<journal.ndjson> ORCSPACE_SNAPSHOT=<snapshot.json> \
///     cargo test --test projection_parity -- --ignored --nocapture
///
/// Kept out of CI: journals carry the user's paths and commands.
#[test]
#[ignore = "needs a real journal: set ORCSPACE_JOURNAL and ORCSPACE_SNAPSHOT"]
fn folding_a_real_journal_matches_typescript() {
    let journal_path = std::env::var("ORCSPACE_JOURNAL").expect("ORCSPACE_JOURNAL");
    let snapshot_path = std::env::var("ORCSPACE_SNAPSHOT").expect("ORCSPACE_SNAPSHOT");

    let entries: Vec<JournalEntry> = std::fs::read_to_string(&journal_path)
        .expect("journal readable")
        .lines()
        .filter(|line| !line.trim().is_empty())
        .map(|line| serde_json::from_str(line).expect("journal line parses"))
        .collect();

    let reference: Value = serde_json::from_str(
        &std::fs::read_to_string(&snapshot_path).expect("snapshot readable"),
    )
    .expect("snapshot parses");
    let clock = Clock(reference["fixedNow"].as_f64().expect("snapshot pins Date.now"));
    let expected = &reference["snapshot"];

    assert_eq!(
        reference["entryCount"].as_u64().unwrap() as usize,
        entries.len(),
        "the snapshot was produced from a different journal"
    );

    let state = fold(entries.iter(), CanvasState::default(), clock);
    let actual_widgets = list_widgets(&state);
    let expected_widgets = expected["widgets"].as_array().expect("widgets");

    assert_eq!(
        actual_widgets.iter().map(|w| w.id.as_str()).collect::<Vec<_>>(),
        expected_widgets
            .iter()
            .map(|w| w["id"].as_str().unwrap())
            .collect::<Vec<_>>(),
        "widget ids or their order differ"
    );

    for (actual, expected) in actual_widgets.iter().zip(expected_widgets) {
        let at = &actual.id;
        assert_eq!(actual.title, expected["title"].as_str().unwrap(), "{at}: title");
        assert_eq!(actual.kind.as_deref(), expected["kind"].as_str(), "{at}: kind");
        assert_eq!(actual.x, number(&expected["x"]), "{at}: x");
        assert_eq!(actual.y, number(&expected["y"]), "{at}: y");
        assert_eq!(actual.w, number(&expected["w"]), "{at}: w");
        assert_eq!(actual.h, number(&expected["h"]), "{at}: h");
        assert_eq!(actual.z, number(&expected["z"]), "{at}: z");
        assert_eq!(actual.version, number(&expected["version"]), "{at}: version");
        assert_eq!(actual.updated_at, number(&expected["updatedAt"]), "{at}: updatedAt");
    }

    assert_eq!(state.camera.x, number(&expected["camera"]["x"]), "camera x");
    assert_eq!(state.camera.y, number(&expected["camera"]["y"]), "camera y");
    assert_eq!(state.camera.zoom, number(&expected["camera"]["zoom"]), "camera zoom");
    assert_eq!(state.strokes.len(), expected["strokes"].as_array().unwrap().len(), "strokes");
    assert_eq!(
        state.connections.len(),
        expected["connections"].as_array().unwrap().len(),
        "connections"
    );
    assert_eq!(state.version, number(&expected["version"]), "canvas version");

    println!(
        "folded {} real entries into {} widgets, matching TypeScript",
        entries.len(),
        actual_widgets.len()
    );
}

/// An image widget has to survive the fold with the two fields that make it an
/// image at all.
///
/// `sanitize_widget` drops a widget whose kind it does not recognise — not just
/// the kind, the whole widget — so a `WIDGET_KINDS` list that has fallen behind
/// the TypeScript one makes every widget of the missing kind vanish on replay.
/// And because `widget.update` rebuilds the widget from `widget_to_value`
/// before applying the patch, any field missing from that round trip is erased
/// by the first move or resize.
#[test]
fn an_image_widget_keeps_its_source_across_create_and_update() {
    let entry = |seq: u64, entry_type: &str, payload: Value| JournalEntry {
        seq,
        at: 1_789_000_000_000 + seq,
        phase: "commit".to_owned(),
        actor_id: "user".to_owned(),
        entry_type: entry_type.to_owned(),
        target: "widget:img1".to_owned(),
        payload: Some(payload),
        version: Some(seq as i64),
        error: None,
        prev_hash: None,
        hash: None,
    };
    let entries = vec![
        entry(
            1,
            "widget.create",
            serde_json::json!({
                "id": "img1",
                "title": "shot.png",
                "kind": "image",
                "x": 10.0, "y": 20.0, "w": 320.0, "h": 240.0, "z": 3.0,
                "imagePath": "C:\\shots\\shot.png",
                "imageName": "shot.png"
            }),
        ),
        entry(2, "widget.update", serde_json::json!({ "x": 40.0 })),
    ];

    let state = fold(entries.iter(), CanvasState::default(), Clock(1_789_000_000_000.0));
    let widgets = list_widgets(&state);

    assert_eq!(widgets.len(), 1, "the image widget must survive the fold");
    let widget = widgets[0];
    assert_eq!(widget.kind.as_deref(), Some("image"));
    assert_eq!(widget.x, 40.0, "the update must apply");
    assert_eq!(widget.image_path.as_deref(), Some("C:\\shots\\shot.png"), "the update must not erase the source");
    assert_eq!(widget.image_name.as_deref(), Some("shot.png"));
}
