import React from 'react';
import {AbsoluteFill, Composition, Img, interpolate, staticFile, useCurrentFrame} from 'remotion';
import {registerRoot} from 'remotion';

const logo = staticFile('orc-logo.png');
const ease = (n) => n * n * (3 - 2 * n);
const fade = (f, start, end) => ease(interpolate(f, [start, start + 18, end - 18, end], [0, 1, 1, 0], {extrapolateLeft: 'clamp', extrapolateRight: 'clamp'}));
const colors = {ink: '#111111', gray: '#6E6E73', line: '#D2D2D7', blue: '#2997FF', green: '#30D158', purple: '#AF52DE', orange: '#FF9F0A'};

function Dot({color}) { return <span style={{width: 11, height: 11, borderRadius: 20, background: color, display: 'inline-block'}}/>; }
function Logo({size = 58}) { return <Img src={logo} style={{width: size, height: size, borderRadius: size * .2}}/>; }
function Nav() { return <div style={{position: 'absolute', top: 42, left: 76, right: 76, display: 'flex', alignItems: 'center', zIndex: 10}}><Logo size={42}/><span style={{fontSize: 23, fontWeight: 650, letterSpacing: -0.7, marginLeft: 13}}>OrcSpace</span><span style={{marginLeft: 'auto', fontSize: 16, color: colors.gray}}>For focused teams</span></div>; }
function Browser({children, x, y, w, h, dark = false}) { return <div style={{position: 'absolute', left: x, top: y, width: w, height: h, background: dark ? '#1D1D1F' : '#FFFFFF', border: `1px solid ${dark ? '#38383A' : colors.line}`, borderRadius: 18, boxShadow: '0 30px 80px rgba(0,0,0,.16)', overflow: 'hidden'}}><div style={{height: 46, display: 'flex', alignItems: 'center', padding: '0 16px', gap: 8, borderBottom: `1px solid ${dark ? '#38383A' : '#E5E5EA'}`}}><Dot color="#FF5F57"/><Dot color="#FFBD2E"/><Dot color="#28C840"/><span style={{fontSize: 13, color: dark ? '#98989D' : colors.gray, marginLeft: 10}}>OrcSpace</span></div>{children}</div>; }
function Canvas({dark = false}) { return <div style={{position: 'absolute', inset: 0, background: dark ? '#1D1D1F' : '#F5F5F7'}}><div style={{position: 'absolute', inset: 0, opacity: .55, backgroundImage: `linear-gradient(${dark ? '#363638' : '#E5E5EA'} 1px, transparent 1px), linear-gradient(90deg, ${dark ? '#363638' : '#E5E5EA'} 1px, transparent 1px)`, backgroundSize: '46px 46px'}}/><div style={{position: 'absolute', inset: 0, background: dark ? 'radial-gradient(circle at 50% 45%, transparent 0, #1D1D1F 75%)' : 'radial-gradient(circle at 50% 45%, transparent 0, #F5F5F7 78%)'}}/></div>; }
function SceneOne({f}) { const a = fade(f, 0, 145); return <AbsoluteFill style={{opacity: a, background: '#F5F5F7'}}><Nav/><div style={{position:'absolute',left:140,top:250}}><div style={{fontSize:24,color:colors.gray,letterSpacing:-.4,marginBottom:24}}>Introducing</div><div style={{fontSize:104,lineHeight:.98,fontWeight:720,letterSpacing:-6,color:colors.ink}}>Your<br/><span style={{color:colors.blue}}>work,</span><br/>connected.</div><div style={{fontSize:24,color:colors.gray,marginTop:36}}>One canvas for your ideas, agents<br/>and everything you ship.</div></div><div style={{position:'absolute',right:90,top:180,width:780,height:660,transform:'rotate(-4deg)'}}><Browser x={72} y={76} w={630} h={420}><Canvas/><div style={{position:'absolute',left:100,top:86,width:170,height:112,borderRadius:14,background:'#FFF',boxShadow:'0 8px 20px #0001',padding:18}}><div style={{fontSize:13,color:colors.gray}}>TODAY</div><div style={{fontSize:21,fontWeight:650,marginTop:11}}>Build the<br/>next thing.</div></div><div style={{position:'absolute',left:330,top:190,width:170,height:118,borderRadius:14,background:'#FFF',boxShadow:'0 8px 20px #0001',padding:18}}><div style={{fontSize:13,color:colors.blue}}>MISSION</div><div style={{fontSize:21,fontWeight:650,marginTop:11}}>Ship v2.0<br/>with the team.</div></div></Browser></div></AbsoluteFill>; }
function SceneTwo({f}) { const a = fade(f, 135, 290); return <AbsoluteFill style={{opacity:a, background:'#000', color:'#FFF'}}><div style={{position:'absolute',left:0,right:0,top:145,textAlign:'center'}}><div style={{fontSize:23,color:'#A1A1A6',marginBottom:25}}>Ideas are better when you can see them.</div><div style={{fontSize:80,fontWeight:720,letterSpacing:-4}}>Everything<br/><span style={{color:'#2997FF'}}>in one place.</span></div></div><div style={{position:'absolute',left:280,top:470,width:1360,height:430}}><Browser x={0} y={0} w={1360} h={430} dark><Canvas dark/><div style={{position:'absolute',left:170,top:70,width:250,height:165,borderRadius:16,background:'#2C2C2E',padding:23,boxShadow:'0 18px 40px #0006'}}><div style={{fontSize:12,color:'#98989D'}}>PRODUCT NOTE</div><div style={{fontSize:26,fontWeight:650,marginTop:14}}>Make it<br/>beautifully<br/>simple.</div></div><div style={{position:'absolute',left:550,top:150,width:270,height:145,borderRadius:16,background:'#2C2C2E',padding:23,boxShadow:'0 18px 40px #0006'}}><div style={{fontSize:12,color:'#30D158'}}>STATUS</div><div style={{fontSize:26,fontWeight:650,marginTop:14}}>On track<br/><span style={{color:'#30D158'}}>●</span></div></div><div style={{position:'absolute',left:970,top:70,width:210,height:180,borderRadius:16,background:'#2C2C2E',padding:23,boxShadow:'0 18px 40px #0006'}}><div style={{fontSize:12,color:'#FF9F0A'}}>NEXT</div><div style={{fontSize:26,fontWeight:650,marginTop:14}}>Ship<br/>the idea.</div></div></Browser></div></AbsoluteFill>; }
function SceneThree({f}) { const a = fade(f, 275, 440); return <AbsoluteFill style={{opacity:a,background:'#F5F5F7'}}><div style={{position:'absolute',left:140,top:230}}><div style={{fontSize:23,color:colors.gray,marginBottom:23}}>Work together.</div><div style={{fontSize:84,lineHeight:1.03,fontWeight:720,letterSpacing:-5,color:colors.ink}}>Your agents<br/><span style={{color:colors.purple}}>move as one.</span></div><div style={{fontSize:23,color:colors.gray,marginTop:34,lineHeight:1.4}}>Plan. Build. Review.<br/>All in the same space.</div></div><div style={{position:'absolute',right:130,top:165,width:730,height:700}}><div style={{position:'absolute',left:280,top:245,width:170,height:170,borderRadius:100,background:'#FFF',border:`2px solid ${colors.ink}`,display:'flex',alignItems:'center',justifyContent:'center',fontSize:19,fontWeight:650,boxShadow:'0 20px 60px #0001'}}>You</div>{[['Claude',colors.orange,0,80],['Codex',colors.blue,450,45],['Grok',colors.purple,460,440],['OpenCode',colors.green,20,490]].map(([name,color,left,top])=><React.Fragment key={name}><div style={{position:'absolute',left:left+75,top:top+40,width:290,height:2,background:color,opacity:.45,transform:`rotate(${left<280?'18':'-18'}deg)`,transformOrigin:'left'}}/><div style={{position:'absolute',left,top,width:150,height:88,borderRadius:18,background:'#FFF',border:`1px solid ${colors.line}`,display:'flex',alignItems:'center',justifyContent:'center',fontSize:18,fontWeight:600,color:colors.ink,boxShadow:'0 16px 36px #0001'}}><span style={{width:10,height:10,background:color,borderRadius:10,marginRight:10}}/>{name}</div></React.Fragment>)}</div></AbsoluteFill>; }
function SceneFour({f}) { const a = fade(f, 425, 590); return <AbsoluteFill style={{opacity:a,background:'#000',color:'#FFF'}}><div style={{position:'absolute',top:160,left:0,right:0,textAlign:'center'}}><div style={{fontSize:23,color:'#A1A1A6',marginBottom:23}}>The command center for getting things done.</div><div style={{fontSize:79,fontWeight:720,letterSpacing:-4}}>From thought<br/><span style={{color:'#30D158'}}>to shipped.</span></div></div><div style={{position:'absolute',left:280,top:505,width:1360,height:400}}><Browser x={0} y={0} w={1360} h={345} dark><div style={{position:'absolute',inset:0,background:'#1D1D1F'}}><div style={{position:'absolute',left:60,top:70,fontFamily:'SFMono-Regular,Consolas,monospace',fontSize:18,lineHeight:2,color:'#D1D1D6'}}><div><span style={{color:'#30D158'}}>agent-02</span> ~ pnpm build</div><div style={{color:'#30D158'}}>✓ 42 tasks complete</div><div><span style={{color:'#30D158'}}>agent-02</span> ~ deploy --production</div><div style={{color:'#2997FF'}}>● live at orcspace.local</div></div><div style={{position:'absolute',right:60,top:70,width:380,height:220,borderRadius:14,background:'#2C2C2E',padding:24}}><div style={{fontSize:13,color:'#98989D'}}>SPRINT PROGRESS</div><div style={{fontSize:47,fontWeight:700,marginTop:14}}>92%</div><div style={{height:8,background:'#48484A',borderRadius:10,marginTop:17}}><div style={{height:8,width:'92%',background:'#30D158',borderRadius:10}}/></div><div style={{fontSize:14,color:'#A1A1A6',marginTop:14}}>Ready to ship</div></div></div></Browser></div></AbsoluteFill>; }
function SceneFive({f}) { const a = fade(f, 575, 765); return <AbsoluteFill style={{opacity:a,background:'#F5F5F7'}}><div style={{position:'absolute',inset:0,background:'radial-gradient(circle at 50% 38%,#DDEEFF,transparent 38%)'}}/><div style={{position:'absolute',top:185,left:0,right:0,textAlign:'center'}}><Logo size={84}/><div style={{fontSize:91,fontWeight:730,letterSpacing:-6,color:colors.ink,marginTop:29}}>Work in your<br/><span style={{color:colors.blue}}>own space.</span></div><div style={{fontSize:25,color:colors.gray,marginTop:32}}>OrcSpace</div><div style={{display:'inline-flex',marginTop:52,padding:'16px 28px',background:colors.ink,color:'#FFF',borderRadius:99,fontSize:18,fontWeight:650,letterSpacing:.3}}>CREATE YOUR CANVAS&nbsp; →</div></div></AbsoluteFill>; }
function Ad(){ const f=useCurrentFrame(); return <AbsoluteFill style={{fontFamily:'-apple-system,BlinkMacSystemFont,"Segoe UI",Arial,sans-serif'}}>{f<150&&<SceneOne f={f}/>} {f>=120&&f<300&&<SceneTwo f={f}/>} {f>=270&&f<450&&<SceneThree f={f}/>} {f>=420&&f<600&&<SceneFour f={f}/>} {f>=570&&<SceneFive f={f}/>}</AbsoluteFill>; }
export const RemotionRoot = () => <Composition id="OrcSpaceAd" component={Ad} durationInFrames={900} fps={30} width={1920} height={1080}/>;
registerRoot(RemotionRoot);
